# Generated by Django 6.0.4 on 2026-04-25 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Gazipur', 'Gazipur'), ('Sylhet', 'Sylhet')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('skills', models.CharField(choices=[('Cooking', 'Cooking'), ('Cleaning', 'Cleaning'), ('Childcare', 'Childcare'), ('Elderly Care', 'Elderly Care'), ('Laundry', 'Laundry'), ('Gardening', 'Gardening'), ('Cooking & Cleaning', 'Cooking & Cleaning'), ('All Rounder', 'All Rounder')], max_length=100)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('salary', models.PositiveIntegerField(help_text='Expected monthly salary in BDT')),
                ('is_verified', models.BooleanField(default=False)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('Hired', 'Hired'), ('Unavailable', 'Unavailable')], default='Available', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='workers/')),
                ('nid_number', models.CharField(blank=True, max_length=20)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message to admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_requests', to='core.worker')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Admin response / new worker assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='core.hiringrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hire', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.hiringrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
