# Generated by Django 6.0.4 on 2026-04-25 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_worker_hiringrequest_replacementrequest_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiringrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin: describe new worker assigned here'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary_agreed', models.PositiveIntegerField()),
                ('terms', models.TextField(default='1. The worker shall report on time every day.\n2. The family shall pay the agreed salary monthly.\n3. Either party may terminate with 7 days notice.\n4. The worker shall be treated with respect.\n5. Disputes shall be resolved through GetBua admin.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='core.hiringrequest')),
            ],
        ),
    ]
