# Generated by Django 6.0.4 on 2026-04-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_hiringrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='proposed_salary',
            field=models.PositiveIntegerField(blank=True, help_text="Salary proposed by family (BDT/month). Leave blank to accept worker's asking salary.", null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Private admin notes — NOT shown to users'),
        ),
        migrations.AddField(
            model_name='worker',
            name='day_off',
            field=models.CharField(choices=[('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Friday & Saturday', 'Friday & Saturday'), ('No Fixed Day Off', 'No Fixed Day Off'), ('Negotiable', 'Negotiable')], default='Friday', max_length=30),
        ),
        migrations.AddField(
            model_name='worker',
            name='extra_notes',
            field=models.TextField(blank=True, help_text='Any extra work details e.g. cooking style, dietary restrictions, etc.'),
        ),
        migrations.AddField(
            model_name='worker',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='worker',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='worker',
            name='guardian_relation',
            field=models.CharField(blank=True, choices=[('Husband', 'Husband'), ('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_hours',
            field=models.CharField(choices=[('Morning (6AM - 12PM)', 'Morning (6AM - 12PM)'), ('Afternoon (12PM - 6PM)', 'Afternoon (12PM - 6PM)'), ('Evening (6PM - 10PM)', 'Evening (6PM - 10PM)'), ('Full Day (8AM - 6PM)', 'Full Day (8AM - 6PM)'), ('Flexible', 'Flexible')], default='Full Day (8AM - 6PM)', max_length=40),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Live-in', 'Live-in'), ('Live-out', 'Live-out')], default='Full Time', max_length=20),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='replacementrequest',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
    ]
