# Generated by Django 6.0.4 on 2026-05-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_hiringrequest_proposed_salary_worker_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days (for short-term)', null=True),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='hire_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Short Term', 'Short Term')], default='Full Time', max_length=20),
        ),
        migrations.AddField(
            model_name='hiringrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, help_text='Used for password reset verification', null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='accepts_short_term',
            field=models.BooleanField(default=False, help_text='Available for short-term/daily hire'),
        ),
        migrations.AddField(
            model_name='worker',
            name='daily_rate',
            field=models.PositiveIntegerField(blank=True, help_text='Per day rate in BDT (for short-term)', null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='min_days',
            field=models.PositiveIntegerField(default=1, help_text='Minimum days for short-term hire'),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='proposed_salary',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='extra_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.PositiveIntegerField(help_text='Monthly salary in BDT'),
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('paid_on', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hiring_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='core.hiringrequest')),
            ],
            options={
                'ordering': ['-year', '-created_at'],
                'unique_together': {('hiring_request', 'month', 'year')},
            },
        ),
    ]
