# Generated by Django 6.0.4 on 2026-05-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hiringrequest_duration_days_hiringrequest_hire_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiringrequest',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='accepts_short_term',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='worker',
            name='daily_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='min_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
    ]
