# Generated by Django 6.0.5 on 2026-05-10 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_hiringrequest_delivery_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='daily_rate_agreed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='total_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='terms',
            field=models.TextField(default='1. The worker shall report on time every day.\n2. The family shall pay the agreed amount.\n3. Either party may terminate with 7 days notice.\n4. The worker shall be treated with respect.\n5. Disputes shall be resolved through GetBua admin.'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('admin_reply', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Replied', 'Replied'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('is_read_by_admin', models.BooleanField(default=False)),
                ('is_read_by_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
