# Generated by Django 6.0.5 on 2026-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contract_daily_rate_agreed_contract_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='area',
            field=models.CharField(blank=True, help_text='Thana / Area within the city', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary_agreed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
